CREATE  TABLE IF NOT EXISTS TBL_COUNTRY (
	NAME VARCHAR(60) NOT NULL,
	PRIMARY KEY(NAME)
)ENGINE = InnoDB;

CREATE  TABLE IF NOT EXISTS TBL_STATE (
	NAME VARCHAR(60) NOT NULL,
	COUNTRY VARCHAR(60) NOT NULL,
	PRIMARY KEY(NAME),
	INDEX FK_STATE_COUNTRY (COUNTRY ASC),
	CONSTRAINT FK_STATE_COUNTRY
		FOREIGN KEY (COUNTRY)
		REFERENCES TBL_COUNTRY (NAME)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)ENGINE = InnoDB;

CREATE  TABLE IF NOT EXISTS TBL_CITY (
	NAME VARCHAR(60) NOT NULL,
	STATE VARCHAR(60) NOT NULL,
	COUNTRY VARCHAR(60) NOT NULL,
	PRIMARY KEY(NAME),
	INDEX FK_CITY_COUNTRY (COUNTRY ASC),
	CONSTRAINT FK_CITY_COUNTRY
		FOREIGN KEY (COUNTRY)
		REFERENCES TBL_COUNTRY (NAME)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
	INDEX FK_CITY_STATE (STATE ASC),
	CONSTRAINT FK_CITY_STATE
		FOREIGN KEY (STATE)
		REFERENCES TBL_STATE (NAME)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)ENGINE = InnoDB;